
#[".oh-my-zsh"]
#  type = "git-repo"
#  url = "https://github.com/ohmyzsh/ohmyzsh"
#  refreshPeriod = "168h"

[".zsh/_git"]
    type = "file"
    url = "https://raw.githubusercontent.com/git/git/master/contrib/completion/git-completion.zsh"
    refreshPeriod = "168h"

[".local/share/completions/history-substring-search.zsh"]
  type = "file"
  url = "https://raw.githubusercontent.com/zsh-users/zsh-history-substring-search/master/zsh-history-substring-search.zsh"
  refreshPeriod = "168h"

[".local/share/vscode-js-debug"]
  type = "git-repo"
  url = "https://github.com/microsoft/vscode-js-debug.git"
  refreshPeriod = "168h"

[".local/share/nvim/site/pack/plugins/start/plenary.nvim"]
  type = "git-repo"
  url = "https://github.com/nvim-lua/plenary.nvim.git"
  refreshPeriod = "168h"

[".local/share/nvim/site/pack/plugins/start/nui.nvim"]
  type = "git-repo"
  url = "https://github.com/MunifTanjim/nui.nvim.git"
  refreshPeriod = "168h"

[".local/share/nvim/site/pack/plugins/start/litee.nvim"]
  type = "git-repo"
  url = "https://github.com/ldelossa/litee.nvim.git"
  refreshPeriod = "168h"

[".local/share/nvim/site/pack/plugins/start/gh.nvim"]
  type = "git-repo"
  url = "https://github.com/ldelossa/gh.nvim.git"
  refreshPeriod = "168h"

[".local/share/nvim/site/pack/plugins/start/nvim-treesitter"]
  type = "git-repo"
  url = "https://github.com/nvim-treesitter/nvim-treesitter.git"
  refreshPeriod = "168h"

[".local/share/nvim/site/pack/plugins/start/lazygit.nvim"]
  type = "git-repo"
  url = "https://github.com/kdheepak/lazygit.nvim"
  refreshPeriod = "168h"

[".local/share/nvim/site/pack/plugins/start/vim-buffest"]
  type = "git-repo"
  url = "https://github.com/rbong/vim-buffest.git"
  refreshPeriod = "168h"

[".local/share/nvim/site/pack/plugins/start/undotree"]
  type = "git-repo"
  url = "https://github.com/mbbill/undotree.git"
  refreshPeriod = "168h"

[".local/share/nvim/site/pack/plugins/start/vim-airline"]
  type = "git-repo"
  url = "https://github.com/vim-airline/vim-airline"
  refreshPeriod = "168h"

[".local/share/nvim/site/pack/plugins/start/vim-airline-themes"]
  type = "git-repo"
  url = "https://github.com/vim-airline/vim-airline-themes"
  refreshPeriod = "168h"

#Plug 'edkolev/tmuxline.vim' ", { 'do': ':TmuxlineSnapshot ~/.dotfiles/shell/tmuxline.sh' }

[".local/share/nvim/site/pack/plugins/start/promptline.vim"]
  type = "git-repo"
  url = "https://github.com/edkolev/promptline.vim"
  refreshPeriod = "168h"

[".local/share/nvim/site/pack/plugins/start/papercolor-theme"]
  type = "git-repo"
  url = "https://github.com/NLKNguyen/papercolor-theme"
  refreshPeriod = "168h"

[".local/share/nvim/site/pack/plugins/start/vim-repeat"]
  type = "git-repo"
  url = "https://github.com/tpope/vim-repeat"
  refreshPeriod = "168h"

[".local/share/nvim/site/pack/plugins/start/vim-fugitive"]
  type = "git-repo"
  url = "https://github.com/tpope/vim-fugitive"
  refreshPeriod = "168h"

[".local/share/nvim/site/pack/plugins/start/vim-surround"]
  type = "git-repo"
  url = "https://github.com/tpope/vim-surround"
  refreshPeriod = "168h"

[".local/share/nvim/site/pack/plugins/start/vim-eunuch"]
  type = "git-repo"
  url = "https://github.com/tpope/vim-eunuch"
  refreshPeriod = "168h"

[".local/share/nvim/site/pack/plugins/start/vim-vinegar"]
  type = "git-repo"
  url = "https://github.com/tpope/vim-vinegar"
  refreshPeriod = "168h"

[".local/share/nvim/site/pack/plugins/start/goyo.vim"]
  type = "git-repo"
  url = "https://github.com/junegunn/goyo.vim"
  refreshPeriod = "168h"

[".local/share/nvim/site/pack/plugins/start/vim-gh-line"]
  type = "git-repo"
  url = "https://github.com/ruanyl/vim-gh-line"
  refreshPeriod = "168h"

#Plug 'junegunn/limelight.vim'
#
#"Plug 'terryma/vim-expand-region'
#"Plug 'terryma/vim-multiple-cursors'
#
#Plug 'nvim-treesitter/nvim-treesitter', {'do': ':TSUpdate'}
#
#"Plug 'sodapopcan/vim-twiggy'
#Plug 'mileszs/ack.vim'
#"Plug 'osyo-manga/vim-over'
#Plug 'triglav/vim-visual-increment'
#Plug 'myusuf3/numbers.vim'
#Plug 'editorconfig/editorconfig-vim'

[".local/share/nvim/site/pack/plugins/start/vim-tmux-navigator"]
  type = "git-repo"
  url = "https://github.com/christoomey/vim-tmux-navigator"
  refreshPeriod = "168h"

[".local/share/nvim/site/pack/plugins/start/vim-tmux-resizer"]
  type = "git-repo"
  url = "https://github.com/melonmanchan/vim-tmux-resizer"
  refreshPeriod = "168h"

[".local/share/nvim/site/pack/plugins/start/better-vim-tmux-resizer"]
  type = "git-repo"
  url = "https://github.com/RyanMillerC/better-vim-tmux-resizer"
  refreshPeriod = "168h"

#
# Style
#
#Plug 'Yggdroot/indentLine'

[".local/share/nvim/site/pack/plugins/start/leap.nvim"]
  type = "git-repo"
  url = "https://github.com/ggandor/leap.nvim"
  refreshPeriod = "168h"

[".local/share/nvim/site/pack/plugins/start/leap-spooky.nvim"]
  type = "git-repo"
  url = "https://github.com/ggandor/leap-spooky.nvim"
  refreshPeriod = "168h"

[".local/share/nvim/site/pack/plugins/start/which-key"]
  type = "git-repo"
  url = "https://github.com/folke/which-key.nvim"
  refreshPeriod = "168h"

[".local/share/nvim/site/pack/plugins/start/fzf-lua"]
  type = "git-repo"
  url = "https://github.com/ibhagwan/fzf-lua.git"
  refreshPeriod = "168h"

[".local/share/nvim/site/pack/plugins/start/firenvim"]
  type = "git-repo"
  url = "https://github.com/glacambre/firenvim.git"
  refreshPeriod = "168h"

[".local/share/nvim/site/pack/plugins/start/nvim-dap"]
  type = "git-repo"
  url = "https://github.com/mfussenegger/nvim-dap.git"
  refreshPeriod = "168h"

[".local/share/nvim/site/pack/plugins/start/nvim-dap-ui"]
  type = "git-repo"
  url = "https://github.com/rcarriga/nvim-dap-ui.git"
  refreshPeriod = "168h"

[".local/share/nvim/site/pack/plugins/start/nvim-dap-virtual-text"]
  type = "git-repo"
  url = "https://github.com/theHamsta/nvim-dap-virtual-text.git"
  refreshPeriod = "168h"


[".local/share/nvim/site/pack/plugins/start/nvim-dap-vscode-js"]
  type = "git-repo"
  url = "https://github.com/mxsdev/nvim-dap-vscode-js.git"
  refreshPeriod = "168h"

#
# Completion
#
[".local/share/nvim/site/pack/plugins/start/coc.nvim"]
  type = "git-repo"
  url = "https://github.com/neoclide/coc.nvim.git"
  branch = "release"
  refreshPeriod = "168h"

#
# Syntax
#
[".local/share/nvim/site/pack/plugins/start/vim-polyglot.nvim"]
  type = "git-repo"
  url = "https://github.com/sheerun/vim-polyglot.git"
  branch = "release"
  refreshPeriod = "168h"

# JavaScript
#"Plug 'pangloss/vim-javascript', { 'for': 'javascript' }
#"Plug 'flowtype/vim-flow', { 'for': 'javascript' }
#" TypeScript
#Plug 'leafgarland/typescript-vim'
#"leafgarland/typescript-vim
#" Mustache
#"Plug 'mustache/vim-mustache-handlebars'
#" Less CSS
#"Plug 'groenewege/vim-less'
#" Elixir
#"Plug 'elixir-lang/vim-elixir'
#" PEG
#Plug 'alunny/pegjs-vim'
#" GLSL
#"Plug 'tikhomirov/vim-glsl'
#" Solidity
#"Plug 'tomlion/vim-solidity'
#
